### ISSUE TITLE
1주차 - MySQL 아키텍처 1부

### ISSUE THREAD

**Issue by ilgolf** [ilgolf/Real_MySQL#1]
1. MySQL 엔진 아키텍쳐
- MySQL 전체 구조 ~ 트랜잭션 지원 메타 데이터

2. InnoDB 스토리지 엔진 아케틱처
- 외래 키 지원
- 자동 데드락 감지
- InnoDB 버퍼 풀 등

**Comment by ilgolf** [comment]
MySQL 아키텍처 : https://golf-dev.tistory.com/6
InnoDB 아키텍처 : https://golf-dev.tistory.com/7

**Comment by tongnamuu** [comment]
https://github.com/tongnamuu/Programming-Interview/blob/master/RealMySql8/Chapter4.md

**Comment by jeeneee** [comment]
https://7124.notion.site/MySQL-b63aefd57a4948f9b27255f94faf15ff

**Comment by rosqxkedrt** [comment]
https://github.com/rosqxkedrt/Real_MY_SQL/issues/1
